version: "3.9"

services:
  pokedex-app:
    build: .
    container_name: pokedex-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL:
      SPRING_DATASOURCE_USERNAME:
      SPRING_DATASOURCE_PASSWORD:
      WEATHER_API_KEY:
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:18
    container_name: postgres
    environment:
      POSTGRES_DB:
      POSTGRES_USER:
      POSTGRES_PASSWORD:
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: redis-server
    ports:
      - "6379:6379"

volumes:
  postgres-data:
