management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,httptrace,prometheus,metrics
  endpoint:
    health:
      show-details: when_authorized
    prometheus:
      access: read_only
  metrics:
    enable:
      all: true
management.endpoints.web.base-path: /actuator
